### PR TITLE
ci: try cargo-hack

### LINKED ISSUE #501: chore: run `cargo-hack` on CI
I think we should start using https://github.com/taiki-e/cargo-hack on CI, like Tokio does. That would’ve probably caught this issue.

_Originally posted by @davidbarsky in https://github.com/tokio-rs/tracing/issues/494#issuecomment-569556563_

### PR DESCRIPTION
**Pull request by baloo**
Fixes #501

## Motivation

I've found multiple compilation error involving non-default features.

## Solution

cargo-hack was a suggested solution (by @davidbarsky and @hawkw) to run compilation checks on all features.

### CODE REVIEW

**Comment by baloo** [comment]
the syntax I use here is not documented to work with azure pipelines, but I wanted to give it a shot anyway.

**Comment by baloo** [comment]
CI was previously running in ~7m. I'll check again when ci is finished to see how much slower this is.

**Comment by baloo** [comment]
Might also be worth checking https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths to save polar bears and not execute useless checks at some point

**Comment by hawkw** [comment]
> Might also be worth checking https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths to save polar bears and not execute useless checks at some point

I think `on` only works for configuring the _whole workflow_ to run if a certain path has changed. For conditionally running the `cargo hack` checks, I think we need to use https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsif instead.

**Comment by hawkw** [comment]
wow, `--feature-powerset` really takes painfully long...

**Comment by hawkw** [comment]
@baloo if you're interested, here's one way we could potentially limit `feature-powerset` to run only if a crate has changes vs master:
```yaml

  cargo-hack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subcrate:
        - tracing-attributes
        - tracing-core
        - tracing-futures
        - tracing-log
        - tracing-macros
        - tracing-serde
        - tracing-tower
        - tracing
        - tracing-subscriber
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@master
    - name: install cargo-hack
      run: cargo install cargo-hack
    - name: cargo hack check
      working-directory: ${{ matrix.subcrate }}
      run: \
        # this command will succeed if `subcrate` has no changes relative to `master`
        git --no-pager diff master.. --quiet -- ${{ matrix.subcrate }} || 
        cargo hack check --feature-powerset --no-dev-deps

```

**Pull request merged**
