### PR TITLE
attributes: speculatively expand when parsing fails

### PR DESCRIPTION
**Pull request by cynecx**
Fixes https://github.com/tokio-rs/tracing/issues/1633.

I intentially did not open a PR because the code isn't really polished and I wasn't sure if that is the right approach. I just needed something quickly to improve my rust-analyzer experience with a project. But here we go...

TODO: Check approach, polish/optimize code (eg. I wasn't sure if cloning a `TokenStream` is "zero/low-cost").

### CODE REVIEW

**Comment by hawkw** [comment]
> TODO: Check approach, polish/optimize code (eg. I wasn't sure if cloning a `TokenStream` is "zero/low-cost").

I'm also not sure about the performance implications of cloning a `TokenStream`...although I notice that the Tokio PR I linked in https://github.com/tokio-rs/tracing/pull/1634#issuecomment-941221144 does it as well: https://github.com/tokio-rs/tokio/pull/4162/files#diff-3778ff38bebb2786ca2b45f4704af832e54cd75369b7b9215eae010cddc58a09R381-R387

Looking at the `syn` docs, though, I noticed the existence of [`ParseBuffer::fork`](https://docs.rs/syn/1.0.80/syn/parse/struct.ParseBuffer.html#method.fork), which seems to be intended for this kind of speculative parsing? I wonder if `ParseBuffer::fork` would provide better performance than `TokenStream::clone`...though I'm not sure if this is the case.

Changing this branch to use `ParseBuffer::fork` might be a bigger change, though, since we'd need to refactor this code so that it all occurs inside of a `syn::Parse` implementation (as this is the only way to get a `ParseStream`; the `ParseStream`/`ParseBuffer` type isn't publicly construct-able).

I don't immediately know whether or not this is worth doing, but I thought it could be good to mention?

**Comment by hawkw** [comment]
ping @cynecx are you still interested in working on moving this forward? 

i'd like to get the IDE support issue fixed as soon as possible, so if you're busy, I'd be happy to take over getting this PR ready to merge. of course, we'd credit your work when merging even if I wrapped up this change. if you're still planning to work on it, that's totally fine --- i just thought i'd offer in the interest of fixing the issue as quickly as possible.

thanks again for your work on this, in either case!

**Comment by cynecx** [comment]
@hawkw Thanks for the feedback. I’ll address the comments when I am back home… :)

**Comment by cynecx** [comment]
@hawkw Btw, I've addressed your comments :)

**Comment by cynecx** [comment]
@hawkw Also, Thank You for adding a proper commit message :D

**Pull request merged**
