### PR TITLE
Appender: Add benchmarks

### PR DESCRIPTION
**Pull request by zekisherif**
## Motivation

We needed benchmarks for tracing-appender

## Solution

Added benches for non_blocking only and for non_blocking which delegates to a rolling file appender.

This is my first time writing a bench :)

### CODE REVIEW

**Comment by hawkw** [comment]
The main reason to benchmark the non-blocking writer, IMO, is to compare its performance with a synchronous (blocking) writer, so that we can assess the performance benefit of this approach. Can you add a benchmark for multiple threads writing synchronously, so that we can compare these?

**Comment by zekisherif** [comment]
> The main reason to benchmark the non-blocking writer, IMO, is to compare its performance with a synchronous (blocking) writer, so that we can assess the performance benefit of this approach. Can you add a benchmark for multiple threads writing synchronously, so that we can compare these?

Sure, will do!

**Comment by bryangarza** [comment]
This PR is really old, but AFAICT, if the branch were to be made up-to-date again, we could merge this.

**Comment by bryangarza** [comment]
Closing since https://github.com/tokio-rs/tracing/pull/2128 was merged :)

**Pull request closed without merging**
