### PR TITLE
chore: port filters to master

### PR DESCRIPTION
**Pull request by davidbarsky**
The `Filter` changes never ended up on the master branch, which is unfortunate. This branch focuses on getting https://github.com/tokio-rs/tracing/pull/1523 compiling on the master branch, but contains a few leftover artifacts that should be removed before this branch is merged.

For the overall porting process, be aware that there are _two_ branches:

- [`david/update-filter-changes`](https://github.com/tokio-rs/tracing/tree/david/update-filter-changes) (this branch) contains the fixes needed to make filters work on the master branch, such as incorrect types, tests, and doctests. However, this branch does yet contain the documentation updates (references to "layers" instead of "subscribers", etc.) needed in order to make documentation coherent.
- [`david/port-filters-to-master`](https://github.com/tokio-rs/tracing/tree/david/port-filters-to-master) contains the subsequent commits that built atop of the `Filter` changes.

Yesterday, I said that `david/update-filter-changes` needs to be merged into `david/port-filters-to-master` as the initial "introducing filters" commit, I no longer think that's correct. I think that `david/update-filter-changes` should be merged into master and `david/port-filters-to-master` should be rebased against the master branch now containing this branch.

It also probably makes sense to rename these branches to something more meaningful and less confusing.

### CODE REVIEW

**Comment by hawkw** [comment]
It looks like there are a few things on this branch that are breaking the MSRV CI job: https://github.com/tokio-rs/tracing/runs/4609658856?check_suite_focus=true#step:4:154

I remember fixing these while working on the filters change, so I'm surprised they're not part of this branch...maybe they were merged in a separate commit?

**Comment by hawkw** [comment]
Oh, I see, this was the commit to `v0.1.x` that fixed the build on MSRV: e59795355798958cf025a6a6eb5ea38cd2e207cf

Looking at the git history on v0.1.x, it looks like there are some other per-layer-filtering related changes that landed in separate PRs. we'll also need to forward-port these:
 - cdb7115e22b342e9ed8c951f3aa9259329f1f746
 - 3b8e680ca42a96d1d24cbd6a1f31f3bb5667d86e
 - b09b368e2945a5e9c4ea6dd9252a6b19c31b5836
 - b420ae7f4ca64e024b17876fb98bd81aeec61753

**Comment by davidbarsky** [comment]
> I remember fixing these while working on the filters change, so I'm surprised they're not part of this branch...maybe they were merged in a separate commit?

If those issues were merged in later as a separate branch, that would explain why the MSRV job is CI job is failing.

**Comment by davidbarsky** [comment]
> Looking at the git history on v0.1.x, it looks like there are some other per-layer-filtering related changes that landed in separate PRs. we'll also need to forward-port these: [redacted for brevity]

Ah, jinx, you responded first and I didn't see it. I'm decently sure that those commits are on [`david/port-filters-to-master`](https://github.com/tokio-rs/tracing/tree/david/port-filters-to-master), but if they're not, I can either include them as part of _this_ PR or as part of the PR that I'll open based on [`david/port-filters-to-master`](https://github.com/tokio-rs/tracing/tree/david/port-filters-to-master). What do you prefer?

**Comment by hawkw** [comment]
> > Looking at the git history on v0.1.x, it looks like there are some other per-layer-filtering related changes that landed in separate PRs. we'll also need to forward-port these: [redacted for brevity]
> 
> Ah, jinx, you responded first and I didn't see it. I'm decently sure that those commits are on [`david/port-filters-to-master`](https://github.com/tokio-rs/tracing/tree/david/port-filters-to-master), but if they're not, I can either include them as part of _this_ PR or as part of the PR that I'll open based on [`david/port-filters-to-master`](https://github.com/tokio-rs/tracing/tree/david/port-filters-to-master). What do you prefer?

Oh, sorry, I didn't see your replies --- my bad! Let's try to get all the commits cherry-picked into one PR, since some of them are necessary for CI to pass?

**Comment by davidbarsky** [comment]
> Oh, sorry, I didn't see your replies --- my bad! Let's try to get all the commits cherry-picked into one PR, since some of them are necessary for CI to pass?

No worries! I'll get those commits over into this PR.

**Comment by davidbarsky** [comment]
whoops, should it done this weekend or early next week. writing docs at work.

**Comment by hawkw** [comment]
@davidbarsky any updates?

**Comment by hawkw** [comment]
Let's also make sure #1959 gets forward-ported as part of this?

**Comment by davidbarsky** [comment]
> Let's also make sure https://github.com/tokio-rs/tracing/pull/1959 gets forward-ported as part of this?

agreed.

**Comment by davidbarsky** [comment]
I'll also need to include https://github.com/tokio-rs/tracing/pull/1973/.

**Comment by davidbarsky** [comment]
I _think_ the last remaining commit to cherrypick is https://github.com/tokio-rs/tracing/pull/1973. After that, I need to resolve the conflicts and go over the documentation to make sure that the phrasing of Layer/Subscriber/Collector is consistent.

I might need help with that part, @hawkw—do you think we can split that up by file?

**Pull request closed without merging**
