### PR TITLE
fix: Update incorrect tracing-futures feature docs

### PR DESCRIPTION
**Pull request by jayvdb**
## Motivation

The docs about the features is incorrect. c.f. https://github.com/tokio-rs/tracing/issues/2799

## Solution

Remove reference to feature `tokio-alpha` which no longer exists, and mention that feature `tokio` is only needed for tokio v0.1 support.

### CODE REVIEW

**Review by davidbarsky — APPROVED** [review]
Oh, appreciate the fix.

**Comment by SpeedReach** [comment]
CI test fail fixed in #2798

**Comment by jayvdb** [comment]
Rebased, and waiting for workflow approval for this and also for https://github.com/tokio-rs/tracing/pull/2800

**Review by mladedav — APPROVED** [review]

**Comment by jayvdb** [comment]
ping @mladedav , do I need to rebase this?

**Comment by mladedav** [comment]
I think @davidbarsky just needs to get around to merging master into this and then merging this into master. I don't think this will have any conflicts so I don't think you need to rebase or manually merge anything.

**Pull request merged**
