### PR TITLE
Convert _all_ the intra-doc links

### PR DESCRIPTION
**Pull request by jyn514**
## Motivation

Closes https://github.com/tokio-rs/tracing/issues/940.

## Solution

Uses ~~a heavily patched version~~ the latest master version of https://github.com/poliorcetics/cargo-intraconv/ to automatically convert the links. Fixes remaining issues by hand.

### CODE REVIEW

**Comment by hawkw** [comment]
It looks like there are a couple link resolution errors failing the CI build: https://app.netlify.com/sites/tracing-rs/deploys/5f7de8e1a5645300075f7ef5

**Comment by jyn514** [comment]
Right, those are https://github.com/poliorcetics/cargo-intraconv/issues/13. I'm hoping to fix it upstream so the fix gets more testing, but if it takes more than a week or so I'll fix the issue manually.

**Comment by poliorcetics** [comment]
I just pushed a fix with tests so hopefully you can use it now without having to check most links manually.

**Comment by jyn514** [comment]
This is finally ready to go! I recommend reading the second commit message - in particular, I couldn't find `SubscriberBuilder::with_filter` anywhere.

Giant thank you to @poliorcetics for making this possible ❤️

**Review by yaahc — APPROVED** [review]
This looks so nice

**Comment by davidbarsky** [comment]
Thanks for doing this! I'd like to ask that we hold off on merging this until #1015 lands because I'm nervous about the rebases already!

**Comment by davidbarsky** [comment]
Good news: #1015 landed!
Bad news: There's a _lot_ of merge conflicts now.
Less bad news: this might not be _too_ painful to resolve.

**Comment by hawkw** [comment]
It looks like this still needs to be rebased?

**Comment by jyn514** [comment]
Yes, rebasing turned out to be a pain (unsurprisingly). Working on it now, thanks for the ping.

**Comment by jyn514** [comment]
Should be fixed now.

A meta note: the terminology is really confusing. There's `Subscribe` which has a main `fmt::Subscriber`, sure, but also a `reload::Subscriber` and `Subscriber` in `tracing-journald`? And you also refer to the `trait Subscribe` as `Subscriber` in several places, and `subscribe` as 'composing' subscribers, and `trait Collect` as 'collectors'. I _think_ I figured it all out, but I'm not 100% sure.

**Comment by jyn514** [comment]
There are still some more links that could be converted (mostly docs.rs or doc.rust-lang.org) but this has enough changes I think I'll save them for a follow-up PR

**Comment by hawkw** [comment]
> Should be fixed now.
> 
> A meta note: the terminology is really confusing. There's `Subscribe` which has a main `fmt::Subscriber`, sure, but also a `reload::Subscriber` and `Subscriber` in `tracing-journald`? And you also refer to the `trait Subscribe` as `Subscriber` in several places, and `subscribe` as 'composing' subscribers, and `trait Collect` as 'collectors'. I _think_ I figured it all out, but I'm not 100% sure.

cc @davidbarsky

**Comment by davidbarsky** [comment]
> A meta note: the terminology is really confusing. There's `Subscribe` which has a main `fmt::Subscriber`, sure, but also a `reload::Subscriber` and `Subscriber` in `tracing-journald`? And you also refer to the `trait Subscribe` as `Subscriber` in several places, and `subscribe` as 'composing' subscribers, and `trait Collect` as 'collectors'. I _think_ I figured it all out, but I'm not 100% sure.

@jyn514 Sorry about that. I'd like to resolve consistencies such as referring to the trait `Subscribe` as a `Subscriber` (formatting choice intentional) and the trait `Collect` as `Collector` before making a proper release. Here's the styleguide that we're considering:

- `Collect` and `Subscribe`, with the code formatting, refer to the traits.
- Collector and subscriber, with _no_ code formatting or special casing, refer to types _implementing_ the `Collect` and `Subscribe` traits.
- Types implementing `Collect` and `Subscribe` should be suffixed with `Collector` and `Subscriber`, respectively.

I was thinking of adding a glossary in a prominent location in documentation that we can point folks to. What do you think?

**Comment by jyn514** [comment]
A glossary sounds really nice :)

**Review by davidbarsky — APPROVED** [review]

**Review by hawkw — APPROVED** [review]
thank you so much for working on this, i know it was probably a bit of a slog! <3

**Comment by jyn514** [comment]
I have to test out rustdoc somehow! :laughing:

**Pull request merged**
