### PR TITLE
Use ManuallyDrop instead of mem::forget

### PR DESCRIPTION
**Pull request by Manishearth**
The current code is UB and LLVM could choose to reuse the stack slot causing a UAF.

## Motivation

UB is bad.

## Solution

Don't do that.

### CODE REVIEW

**Comment by davidbarsky** [comment]
uh oh. i'm headed to the airport for a vacation, but I started the CI for this.

i'm guessing Miri would've caught this?

**Comment by Manishearth** [comment]
no idea!

**Review by hawkw — APPROVED** [review]

**Comment by hawkw** [comment]
Wait, this is weird...that `into_inner` function only added the use of `ManuallyDrop` in https://github.com/tokio-rs/tracing/pull/2562...which should have been reverted (as adding the `Drop` impl was an unintentionally breaking change). Why didn't the `into_inner` function just get reverted back to the original implementation, which was safe and did not use `ManuallyDrop` at all...?

**Comment by nixpulvis** [comment]
Gotta love functions that include a [Safety](https://doc.rust-lang.org/std/mem/fn.forget.html#safety) section which aren't marked as `unsafe`.

**Pull request merged**
