### PR TITLE
docs: fix typo causing CI doc check warnings

### PR DESCRIPTION
**Pull request by salewski**
## Motivation

I noticed complaints in the doc checks upon CI deployments, and at first misread them as being the cause of some "Deployment failed" errors. It turns out that they were not the cause, but this PR does fix the doc check error.

There are several separate "Deploy failed" errors, all the same. From the deploy logs of one of them:

```console
    $   curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly --profile minimal && source $HOME/.cargo/env && RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps
    ...
    11:46:24 PM: warning: unresolved link to `Makewriter`
    11:46:24 PM:    --> tracing-subscriber/src/fmt/writer.rs:153:58
    11:46:24 PM:     |
    11:46:24 PM: 153 | /// A writer that erases the specific [`io::Write`] and [`Makewriter`] types being used.
    11:46:24 PM:     |                                                          ^^^^^^^^^^^^ no item named `Makewriter` in scope
    11:46:24 PM:     |
    11:46:24 PM:     = note: `#[warn(broken_intra_doc_links)]` on by default
    11:46:24 PM:     = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
    11:46:24 PM: warning: 1 warning emitted
    11:46:25 PM:  Documenting tracing-flame v0
    ...
```

## Solution

Fix single character typo: "Makewriter" => "MakeWriter".

### CODE REVIEW

**Comment by hawkw** [comment]
Thanks for the fix!

I notice [the netlify docs build is still failing](https://app.netlify.com/sites/tracing-rs/deploys/5fd05fd9ca0a7600077a05d9). It's possible something is also broken in our configs? @davidbarsky can you take a look?

**Comment by davidbarsky** [comment]
We're able to successfully document the package, bu Netlify seems to fail at this:

> 12:28:35 AM: Failed during stage 'building site': Deploy directory 'target/doc' does not exist

**Comment by hawkw** [comment]
#1131 should fix other Netlify build issues, so we should then be able to get a successful docs build.

**Review by davidbarsky — COMMENTED** [review]
Approved, modulo a rebase against the master branch to pick up the changes in #1131.

**Comment by salewski** [comment]
> Approved, modulo a rebase against the master branch to pick up the changes in #1131.

Thanks @davidbarsky  I just force pushed my rebase against current master.

**Comment by salewski** [comment]
> > Approved, modulo a rebase against the master branch to pick up the changes in #1131.
> 
> Thanks @davidbarsky I just force pushed my rebase against current master.

They all went green this time.

**Comment by salewski** [comment]
Oops, think I hit the wrong button there and accidentally closed this.

**Review by hawkw — APPROVED** [review]
:+1:

**Pull request merged**
