### PR TITLE
chore: Backports to v0.1.x

### PR DESCRIPTION
**Pull request by davidbarsky**
Some additional backports.

(Let's see if CI passes first—I suspect that it won't...)

### CODE REVIEW

**Comment by hawkw** [comment]
looks like there are some surprising `clippy` warnings: https://github.com/tokio-rs/tracing/runs/8255803899?check_suite_focus=true

**Comment by davidbarsky** [comment]
> looks like there are some surprising clippy warnings: https://github.com/tokio-rs/tracing/runs/8255803899?check_suite_focus=true

Yeah, they are. I"ll try taking a look tomorrow morning.

**Comment by hawkw** [comment]
@davidbarsky any updates on this?

**Comment by hawkw** [comment]
The reason for the Clippy failures is that PR #2269 wasn't backported correctly, and the `on_register_dispatch` method was never actually being called, resulting in dead code. I've fixed that.

We probably should have had a test that `on_register_dispatch` is called when registering a dispatcher, as that would have caught this...

**Comment by davidbarsky** [comment]
sorry, i thought i replied; thanks for catching my mistake there.

**Pull request merged**
