### PR TITLE
Add `record_bytes` to `Visit`

### PR DESCRIPTION
**Pull request by mattrutherford**
## Motivation

We use a lot of data that's encoded as bytes that we would like to record to spans and events. While it's possible to use the debug representation, this is not so efficient.

## Solution

Add `record_bytes` method to the `Visit` trait which defaults to use `record_debug` in the same way as the existing methods.

### CODE REVIEW

**Comment by hawkw** [comment]
Since this is a `tracing-core` change, it would be nice to get @carllerche's approval on this.

**Comment by mattrutherford** [comment]
Thanks - if the change is acceptable, I can add more documentation / examples.

**Comment by dvdplm** [comment]
@hawkw this one would be good to get in some day soon. Anything I can do to help expedite the review here? 

:)

**Comment by carllerche** [comment]
I don't have a problem w/ this.

**Comment by mattrutherford** [comment]
This is still something that's going to be useful - anything I can do to move it along? Or any concerns?

**Comment by dvdplm** [comment]
Any news on when this might get merged?

**Comment by bryangarza** [comment]
After a rebase, this could probably be merged

**Pull request closed without merging**
