### PR TITLE
fixup missing repository links on crates.io

### PR DESCRIPTION
**Pull request by baloo**

### CODE REVIEW

**Comment by baloo** [comment]
tracing-core does not, so I'm not sure. @hawkw ?

**Comment by hawkw** [comment]
@davidbarsky @baloo the cargo docs say it should be the repo base url, though I'm not sure if this is a big deal.

**Comment by davidbarsky** [comment]
Then that feels reasonable to me. No issues.

**Comment by hawkw** [comment]
merged! thanks again @baloo!

**Pull request merged**
