### PR TITLE
Convert even more intra-doc links

### PR DESCRIPTION
**Pull request by jyn514**
## Motivation

#940

## Solution

This changes the docs.rs links, many of which were broken (or would have been broken on the next release). It also converts some links I missed the first time (maybe they were added after I opened the PR?).

### CODE REVIEW

**Comment by jyn514** [comment]
As a side note - have you considered running [`cargo deadlinks`](https://github.com/deadlinks/cargo-deadlinks/) or something similar in CI? That would have caught a lot of these broken links, I think.

(disclaimer: I maintain cargo-deadlinks and want more people to use it :P)

**Comment by hawkw** [comment]
> As a side note - have you considered running [`cargo deadlinks`](https://github.com/deadlinks/cargo-deadlinks/) or something similar in CI? That would have caught a lot of these broken links, I think.

This is the first I've heard of `cargo deadlinks`, but I think running it sounds like a great idea! Do you have the time to set up a CI job that runs it?

**Comment by jyn514** [comment]
Absolutely! I'll make a follow-up PR with that.

**Review by hawkw — APPROVED** [review]
:heart:

**Pull request merged**
