### PR TITLE
chore: backport #2750

### PR DESCRIPTION
**Pull request by davidbarsky**
Backporting #2750, see that PR for details.

### CODE REVIEW

**Review by hawkw — APPROVED** [review]

**Comment by hawkw** [comment]
wait now our docs build is wedged??? https://app.netlify.com/sites/tracing-rs/deploys/6528827cf9fff5000864d092

**Comment by davidbarsky** [comment]
> wait now our docs build is wedged??? https://app.netlify.com/sites/tracing-rs/deploys/6528827cf9fff5000864d092

I'll fix that shit as part of _this_ PR.

**Comment by davidbarsky** [comment]
> > wait now our docs build is wedged??? https://app.netlify.com/sites/tracing-rs/deploys/6528827cf9fff5000864d092
> 
> I'll fix that shit as part of _this_ PR.

Fixed in https://github.com/tokio-rs/tracing/pull/2753, sorry.

**Comment by hawkw** [comment]
cool, that one might have been my fault.

**Comment by davidbarsky** [comment]
> cool, that one might have been my fault.

no worries at all, my eyes tend to glaze over at times.

**Pull request merged**
