### PR TITLE
Switch to even more intra-doc links

### PR DESCRIPTION
**Pull request by jyn514**
## Motivation

#940 

## Solution

This converts some more links found while trying to debug the link failures in https://github.com/tokio-rs/tracing/pull/1078. Unfortunately it didn't fix the failures, but it's a useful change so I split it out into a separate PR.

### CODE REVIEW

**Comment by jyn514** [comment]
(If you want this to land as part of https://github.com/tokio-rs/tracing/pull/1078 instead, that's fine too.)

**Comment by jyn514** [comment]
I think this is as ready for review as it will ever be, https://github.com/tokio-rs/tracing/pull/1078 has a lot of broken links due to rustdoc bugs so I wouldn't wait on that.

**Review by davidbarsky — APPROVED** [review]
This LGTM! Thanks for making these changes.

**Comment by jyn514** [comment]
Hmm, I'm not sure why CI is failing - it says the windows job was cancelled? I can't find any relevant logs.

**Comment by davidbarsky** [comment]
Yup, I canceled the Windows job by accident. Lemme restart it.

**Comment by jyn514** [comment]
I think this is ready to merge :)

**Comment by davidbarsky** [comment]
Done, thanks!

**Pull request merged**
