### PR TITLE
Support dash in target names

### PR DESCRIPTION
**Pull request by bkchr**
This adds support for having dashes in log target names, like:
`target-name=info`

## Motivation

We are using log targets with dashes in our project.

## Solution

Extend the target parsing regex to support dashes.

### CODE REVIEW

**Review by hawkw — APPROVED** [review]
This looks good to me!

It might be worth adding a note to the docs that when a crate's name has a dash in it, the default target for events in that crate will be the crate's _module path_ as it appears in Rust code, so the dash will be turned into an underscore. Dashes will only appear in targets when you write an explicit target string like 
```rust
tracing::info!(target: "target-name", ...);
```

**Comment by davidbarsky** [comment]
This seems like a reasonable change, but does `rust-lang/log` support hyphens in their target names?

I would assume that targets follow legal Rust syntax and I don't believe hyphens are.

**Comment by bkchr** [comment]
> This seems like a reasonable change, but does `rust-lang/log` support hyphens in their target names?
> 
> I would assume that targets follow legal Rust syntax and I don't believe hyphens are.

We used before `env_logger` and that supported dashes.

**Comment by bkchr** [comment]
> This looks good to me!
> 
> It might be worth adding a note to the docs that when a crate's name has a dash in it, the default target for events in that crate will be the crate's _module path_ as it appears in Rust code, so the dash will be turned into an underscore. Dashes will only appear in targets when you write an explicit target string like
> 
> ```rust
> tracing::info!(target: "target-name", ...);
> ```

Can you give me a pointer where I should add this?

**Comment by bkchr** [comment]
And any idea why macos is failing? Is this a known error?

**Comment by hawkw** [comment]
> And any idea why macos is failing? Is this a known error?

That test fails spuriously sometimes...I really need to fix that. I went ahead and restarted CI for you.

> > This looks good to me!
> > It might be worth adding a note to the docs that when a crate's name has a dash in it, the default target for events in that crate will be the crate's _module path_ as it appears in Rust code, so the dash will be turned into an underscore. Dashes will only appear in targets when you write an explicit target string like
> > ```rust
> > tracing::info!(target: "target-name", ...);
> > ```
> 
> Can you give me a pointer where I should add this?

Maybe in the ["Usage Notes" section](https://github.com/tokio-rs/tracing/blob/04bbb15d3a4c0f74027312b8951484807ca22d48/tracing-subscriber/src/filter/env/mod.rs#L61)?

**Comment by bkchr** [comment]
@hawkw done

**Comment by bkchr** [comment]
And @hawkw would it be possible to release this afterwards relative shortly?

**Review by hawkw — APPROVED** [review]

**Comment by hawkw** [comment]
> And @hawkw would it be possible to release this afterwards relative shortly?

If you need to get this published soon, you'll need to open another PR to merge this into the `v0.1.x` branch as well. The `master` branch currently contains breaking changes for the upcoming `tracing` 0.2 release (which should be out in a couple of weeks); in order to release these changes immediately they need to be backported to the current version.

Since I've already approved this PR, though, I'll happily merge the same changes into v0.1.x!

**Pull request merged**
