### PR TITLE
subscriber: prepare 0.0.1-alpha.2 release

### PR DESCRIPTION
**Pull request by davidbarsky**
Prepare a 0.0.1-alpha.2 release with the changes in #223. Let me know if I should bundle any other changes.

### CODE REVIEW

**Comment by davidbarsky** [comment]
Hmm, I think I should bundle the changes in tracing-fmt.

**Comment by davidbarsky** [comment]
@hawkw I'd be happy to push those unpublished packages out as well, as the Filter/Reload layers are very handy.

**Comment by davidbarsky** [comment]
Chat with Eliza on Gitter:

> let’s do the following:
> - cut an alpha.2 release of tracing-fmt
> - here is what we need to publish tracing-futures: https://github.com/tokio-rs/tracing/milestone/6
> - i’m fine with publishing tracing-tower if we add docs and give it a thorough naming pass as well
> - i can go and get the matchers crate i wrote ready to publish as well

**Comment by davidbarsky** [comment]
I just a alpha.2 release of tracing-fmt, so one item is ticked off.

**Comment by hawkw** [comment]
`tracing-futures` 0.0.1.alpha.1 is also shipped.

**Comment by hawkw** [comment]
> [...] I noticed a bit of a bug in the field-filtering code that I'll fix before publishing the release.

Never mind, I was totally wrong; I misread some of my own code. The test I added in  #239 would catch this issue if it existed.

**Pull request merged**
