### PR TITLE
chore: add an issue template for questions

### PR DESCRIPTION
**Pull request by davidbarsky**
Now that we have discussions enabled, this thing _should_ direct folks to create a discussion instead.

### CODE REVIEW

**Comment by jbr** [comment]
Suggestion: I tried a few variations on exactly this and ended up with [this](https://github.com/trillium-rs/trillium/blob/main/.github/ISSUE_TEMPLATE/config.yml)

**Comment by davidbarsky** [comment]
@jbr Ah, that might require us migrating to the new yaml-based approach for this. I'd be happy to try if @hawkw is interested?

**Comment by hawkw** [comment]
sure, go for it!

**Comment by hawkw** [comment]
@davidbarsky any updates on this?

**Comment by hawkw** [comment]
pinging this again

**Comment by bryangarza** [comment]
@davidbarsky still need this or can we close?

**Comment by davidbarsky** [comment]
To make use of this, we'd need to move to the V2 version of GitHub's CI config, which is why this stalled. I think we should that as part of a different PR, not this, and I'd rather not futz with YAML this second. I'll close this in the meantime.

**Pull request closed without merging**
