### PR TITLE
opentelemetry: Backport update to otel v0.12.x (#1200)

### PR DESCRIPTION
**Pull request by jtescher**
Backport #1200 into `v0.1.x`

### CODE REVIEW

**Comment by jtescher** [comment]
@davidbarsky should we backport #1195 as well?

**Comment by davidbarsky** [comment]
@jtescher If it unblocks this branch, yeah. That shouldn't involve an MSRV bump.

**Comment by davidbarsky** [comment]
@jtescher You should be unblocked now as v0.1.0 now has #1208 with the clippy/deprecation fixes.

**Comment by jtescher** [comment]
@davidbarsky great! ready for review now that tests are passing

**Review by hawkw — APPROVED** [review]

**Pull request merged**
