### PR TITLE
Switch to intra-doc links in tracing-core

### PR DESCRIPTION
**Pull request by jyn514**
## Motivation

This caught multiple broken links in the documentation. Partially addresses https://github.com/tokio-rs/tracing/issues/940.

## Solution

Use intra-doc links so rustdoc will give a loud warning if the documentation has errors.

### CODE REVIEW

**Comment by jyn514** [comment]
This can probably be simplified a lot more, my regex is not very smart. I'll try to take a look tomorrow.

**Review by hawkw — APPROVED** [review]
looks good to me, thanks so much for working on this (admittedly kinda thankless) task! :)

**Review by davidbarsky — APPROVED** [review]
Thanks for doing this thing!

**Comment by jyn514** [comment]
Haha, don't thank me yet! Like 90% of these reference links can be removed still since they're in scope :)

**Pull request merged**
