### PR TITLE
docs: Fix typo

### PR DESCRIPTION
**Pull request by dzvon**
There is no struct named `Subscriber`, I think the `Subscriber` here is a trait.

### CODE REVIEW

**Review by hawkw — APPROVED** [review]
thanks, good catch!

we should probably change these to intra-docs links eventually so we don't have this kind of problem...

**Comment by dzvon** [comment]
Thanks for your review, Eliza.

So should I close this PR?

**Comment by hawkw** [comment]
> Thanks for your review, Eliza.
> 
> 
> 
> So should I close this PR?

whoops, i meant to merge this but forgot to click "merge"!

**Comment by dzvon** [comment]
Hahaha, I thought you were going to refuse me. :D So sad.

**Pull request merged**
