### PR TITLE
opentelemetry: backport prepare for 0.15.0 release

### PR DESCRIPTION
**Pull request by jtescher**
Backport #1501 into `v0.1.x`

### CODE REVIEW

**Comment by hawkw** [comment]
ugh...looks like a `clap` update broke our MSRV. what even pulls in `clap`? i'm guessing it's for an example?

**Comment by jtescher** [comment]
Yeah looks like a couple examples and [criterion](https://crates.io/crates/criterion/0.3.5/dependencies).

**Comment by hawkw** [comment]
> Yeah looks like a couple examples and [criterion](https://crates.io/crates/criterion/0.3.5/dependencies).

bleh, okay, I'll try to get the build fixed up.

**Comment by hawkw** [comment]
CI ought to pass now...

**Review by hawkw — APPROVED** [review]

**Pull request merged**
