### PR TITLE
Use less allocations in recording `Display` and `Error` values

### PR DESCRIPTION
**Pull request by hrxi**
Use the fact that the `Debug` implementation of `DisplayValue`
corresponds to the `Display` implementation of the wrapped type. This
means that the string allocation of the `Display`ed type can be avoided
entirely.

### CODE REVIEW

**Comment by hawkw** [comment]
I don't believe this actually avoids any allocations, as `format_args!` doesn't allocate a `String`, it just returns `fmt::Arguments` that implements `Debug`; it's `format!` that allocates a string.

But, avoiding the macros is a bit nicer when they're not necessary, so I would be fine making this change.

**Comment by hrxi** [comment]
You're right, I was thinking of `format!` when I made this change. Should I adjust the commit message?

**Comment by davidbarsky** [comment]
> You're right, I was thinking of format! when I made this change. Should I adjust the commit message?

We can change the commit message when we merge + squash—don't worry about that.

**Review by hawkw — APPROVED** [review]
Going to go ahead and merge this --- although it doesn't actually reduce allocations, I think it's a bit nicer to avoid the unnecessary use of `format_args!` macros.

**Comment by hawkw** [comment]
huh, seems like the nightly compiler ICEs on this PR for some reason --- i wonder if that happens on main, too? https://github.com/tokio-rs/tracing/runs/5573114704?check_suite_focus=true

**Comment by hrxi** [comment]
@hawkw Current nightly is broken, CI runs also fail on other repos with that ICE.

**Pull request merged**
