### PR TITLE
chore: move tracing-opentelemetry from the master branch

### PR DESCRIPTION
**Pull request by davidbarsky**
This PR removes tracing-opentelemetry to a dedicated repo located at https://github.com/tokio-rs/tracing-opentelemetry. (Note that at time of writing this PR, the new repo has not be made public). We're moving tracing-opentelemetry to a dedicated repository for the following reasons:
1. opentelemetry's MSRV is higher than that of `tracing`'s.
2. more importantly, the main `tracing` repo is getting a bit unweildy and it feels unreasonable to maintain backports for crates that integrate with the larger tracing ecosystem.

(https://github.com/tokio-rs/tracing-opentelemetry does not have the examples present in this repo; this will occur in a PR that will be linked from _this_ PR.)

### CODE REVIEW

**Comment by punkeel** [comment]
I understand you didn't migrate the examples yet. I believe if you remove the `tracing_opentelemetry` dependency from `examples/Cargo.toml`, you should also remove the following example files (otherwise tests will fail):

- [examples/examples/opentelemetry.rs](https://github.com/tokio-rs/tracing/blob/a0126b2e/examples/examples/opentelemetry.rs)
- [examples/examples/opentelemetry-remote-context.rs](https://github.com/tokio-rs/tracing/blob/a0126b2e/examples/examples/opentelemetry-remote-context.rs)

and remove the mentions from [examples/README.md](https://github.com/tokio-rs/tracing/blob/a0126b2e/examples/README.md?plain=1#L68-L73)

**Comment by davidbarsky** [comment]
> I understand you didn't migrate the examples yet. I believe if you remove the tracing_opentelemetry dependency from examples/Cargo.toml, you should also remove the following example files (otherwise tests will fail):

Yup, I meant to say that I'd be relying on CI to catch this, but was too tired and forgot. Those will be moved over to the new repo.

**Comment by davidbarsky** [comment]
I'll update the docs and example to point to the new repo. Do you mind making the new repo public in the meantime?

**Comment by hawkw** [comment]
> Do you mind making the new repo public in the meantime?

@davidbarsky done, I was gonna do it once the code was moved over but then I forgot, whoops. BTW, you also have the admin bit for that repo.

**Comment by hawkw** [comment]
@davidbarsky any updates on changing/removing the examples? I'd really like to get this merged.

**Comment by davidbarsky** [comment]
netlify is failing due to:

```
6:10:24 PM: Failed during stage 'preparing repo': error checking for ref: : fatal: unable to access 'https://github.com/tokio-rs/tracing/': Failed to connect to github.com port 443: Connection refused
 ```
 
I'm sure it'll be fixed soon. I'll clippy here as well.

**Review by hawkw — APPROVED** [review]
you love to see it!

**Pull request merged**
